version: '2'

services:

  data:
    image: silintl/data-volume:latest
    volumes:
      - ./:/data
    privileged: true

  frontend:
    build: .
    command: bash -c "grunt serve"
    volumes_from:
      - data
    ports:
      - "9000:9000"

  mock-server:
    image: johnlee/api-mock:latest
    volumes: 
      - ./mock-server:/mock/
    ports: 
      - "3000:3000"