version: '2'

services:

  frontend:
    build: .
    working_dir: /data
    ports:
      - "9000:9000"

  frontend-mock:
    build: .
    working_dir: /data
    ports:
      - "9000:9000"
    command: ["grunt", "init", "backend:mock", "serve"]

  mock-server:
    image: silintl/api-mock:latest
    volumes:
      - ./selenium-test/mock-server:/mock/
    ports:
      - "3000:3000"
